from __future__ import annotations

RECORDING_STATUS_QUEUED = "Queued"
RECORDING_STATUS_PROCESSING = "Processing"
RECORDING_STATUS_NEEDS_REVIEW = "NeedsReview"
RECORDING_STATUS_READY = "Ready"
RECORDING_STATUS_PUBLISHED = "Published"
RECORDING_STATUS_QUARANTINE = "Quarantine"
RECORDING_STATUS_FAILED = "Failed"

RECORDING_STATUSES = (
    RECORDING_STATUS_QUEUED,
    RECORDING_STATUS_PROCESSING,
    RECORDING_STATUS_NEEDS_REVIEW,
    RECORDING_STATUS_READY,
    RECORDING_STATUS_PUBLISHED,
    RECORDING_STATUS_QUARANTINE,
    RECORDING_STATUS_FAILED,
)

JOB_STATUS_QUEUED = "queued"
JOB_STATUS_STARTED = "started"
JOB_STATUS_FINISHED = "finished"
JOB_STATUS_FAILED = "failed"

JOB_STATUSES = (
    JOB_STATUS_QUEUED,
    JOB_STATUS_STARTED,
    JOB_STATUS_FINISHED,
    JOB_STATUS_FAILED,
)

JOB_TYPE_INGEST = "ingest"
JOB_TYPE_PRECHECK = "precheck"
JOB_TYPE_STT = "stt"
JOB_TYPE_DIARIZE = "diarize"
JOB_TYPE_ALIGN = "align"
JOB_TYPE_LANGUAGE = "language"
JOB_TYPE_LLM = "llm"
JOB_TYPE_METRICS = "metrics"
JOB_TYPE_PUBLISH = "publish"
JOB_TYPE_CLEANUP = "cleanup"

JOB_TYPES = (
    JOB_TYPE_INGEST,
    JOB_TYPE_PRECHECK,
    JOB_TYPE_STT,
    JOB_TYPE_DIARIZE,
    JOB_TYPE_ALIGN,
    JOB_TYPE_LANGUAGE,
    JOB_TYPE_LLM,
    JOB_TYPE_METRICS,
    JOB_TYPE_PUBLISH,
    JOB_TYPE_CLEANUP,
)

DEFAULT_RQ_QUEUE_NAME = "lan-transcriber"
DEFAULT_REQUEUE_JOB_TYPE = JOB_TYPE_PRECHECK

__all__ = [
    "RECORDING_STATUS_QUEUED",
    "RECORDING_STATUS_PROCESSING",
    "RECORDING_STATUS_NEEDS_REVIEW",
    "RECORDING_STATUS_READY",
    "RECORDING_STATUS_PUBLISHED",
    "RECORDING_STATUS_QUARANTINE",
    "RECORDING_STATUS_FAILED",
    "RECORDING_STATUSES",
    "JOB_STATUS_QUEUED",
    "JOB_STATUS_STARTED",
    "JOB_STATUS_FINISHED",
    "JOB_STATUS_FAILED",
    "JOB_STATUSES",
    "JOB_TYPE_INGEST",
    "JOB_TYPE_PRECHECK",
    "JOB_TYPE_STT",
    "JOB_TYPE_DIARIZE",
    "JOB_TYPE_ALIGN",
    "JOB_TYPE_LANGUAGE",
    "JOB_TYPE_LLM",
    "JOB_TYPE_METRICS",
    "JOB_TYPE_PUBLISH",
    "JOB_TYPE_CLEANUP",
    "JOB_TYPES",
    "DEFAULT_RQ_QUEUE_NAME",
    "DEFAULT_REQUEUE_JOB_TYPE",
]
